### ISSUE TITLE
Many bugs #1.3.1

### ISSUE THREAD

**Issue by HeertzMC** [vik1395/ProtectionStones#1]
I type "/ps tp player 1" this says "you only have 0 protected regions!" and after "Could not find protected region!"
The players have put their sponge again but /Ps tp not work
/ps home sometimes does not work
/ps count not work

Player can't add offline players (not online in the server) with /Ps add and /Ps addowner and /Ps remove
http://pastebin.com/7zPQgvgh
http://pastebin.com/h1EBuq2J

ProtectionStones spams "1" in my console
http://prntscr.com/83k4g2

---------
Please make "/ps home" run as "/ps home '1' "
Add permission per world or an option to disable in specified worlds
---------

Thanks for read! regards!

**Comment by vik1395** [comment]
Ah, thanks for pointing that out. Ill fix them as soon as possible and post and update :)

**Comment by vik1395** [comment]
Hey, just wanted to let you know all the bugs you've posted have been fixed in the new update (1.3.2). Thanks for reporting!
