### ISSUE TITLE
All players (including staff) cannot place protect block.

### ISSUE THREAD

**Issue by Tehtafara0** [vik1395/ProtectionStones#2]
When someone places a protect block down, it says "This area is now protected" and the block dissapears.

**Comment by EvilOlaf** [comment]
That's the expected behavior. Where is the issue?

**Comment by Tehtafara0** [comment]
The block dissapears and the area is not protected too.

**Comment by vik1395** [comment]
Hey, can you please post the error log (if any), your current protectionstones config and the worldguard and bukkit/spigot versions
