### ISSUE TITLE
/ps commands

### ISSUE THREAD

**Issue by cricketcricketcricket** [vik1395/ProtectionStones#5]
a lot of the commands are not working , says command not found. I do not think placing protection stines down is working either, going to try something else and let u know

**Comment by cricketcricketcricket** [comment]
also in config I changed priority to 1 but it still puts it as 0 when I put a block down

**Comment by cricketcricketcricket** [comment]
my error, have to have a region first lol, but the priority thing is still not working

**Comment by vik1395** [comment]
Ah alright, Ill check that out and see whats wrong. Could you please tell me any other issues you are facing and attach some error logs? Thanks :)

**Comment by cricketcricketcricket** [comment]
Hi, no errors on console. in the PS config i set the default Priority to 1, so i can have underlying control via worldguard with a priority 0. But when I put down a protection stone it creates a region with priority 0 still. not a priority 1 like in the PS config I had set

**Comment by vik1395** [comment]
The priority issue has been fixed in the new update (1.3.2). Please update your plugin. Thanks! :)
