### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TheChampTF** [vik1395/ProtectionStones#6]
Add support for several types.

Need different dimensions of claims. Is this possible to add?

**Comment by vik1395** [comment]
Try using /ps view for dimensions. It places 4 glass blocks on all corners of the protected region for 30 seconds. As for support for multiple types, I will be adding it soon

**Comment by TheChampTF** [comment]
Okay, sounds good. Thanks (:

**Comment by TheChampTF** [comment]
@vik1395 Any eta. on release of support for multiple types?
